version: "3"
services:
  web:
    build: .
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - CONTACT_PHONE=${CONTACT_PHONE}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure
  db:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'mysecretpassword'
      - POSTGRES_DB:'mybase'
    ports:
      - "5432:5432"